name: weather_tdd_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^0.13.5
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.2
  build_runner: ^2.1.2
  mockito: ^5.0.15
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
